---

- name: Removing previous Docker installations
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ old_docker_packages_to_remove }}"

- name: Install Trusty Tahr (Ubuntu 14.04) prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_ubuntu_trusty_packages }}"
  when: ansible_distribution_version == '14.04'

- name: Updating and upgrading apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Installing prerequisite packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_ubuntu_packages }}"


- name: Adding Docker CE official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Adding 'stable' Docker CE repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Installing Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes

